export const LANGUAGES = {
  en: {
    welcome: "Welcome to Zeyago Ride",
    continueRider: "Continue as Rider",
    continueDriver: "Continue as Driver",
    phoneAuth: "Phone Authentication",
    enterPhone: "Enter your phone number",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    riderHome: "Where to?",
    requestRide: "Request Ride",
    fareEstimate: "Fare Estimate",
    driverDashboard: "Driver Dashboard",
    goOnline: "Go Online",
    goOffline: "Go Offline",
    earnings: "Earnings",
    history: "History",
    adminDashboard: "Admin Dashboard",
    stats: "Statistics",
    users: "Users",
    rides: "Rides",
    resendOtp: "Resend OTP",
    personal: "Personal",
    business: "Business",
    rewards: "Rewards",
    points: "Points",
    safetyPin: "Safety PIN",
    verifyPin: "Verify PIN",
    startTrip: "Start Trip",
    completeTrip: "Complete Trip",
    arrive: "I have arrived",
  },
  am: {
    welcome: "እንኳን ወደ ዘያጎ ራይድ በሰላም መጡ",
    continueRider: "እንደ ተጓዥ ይቀጥሉ",
    continueDriver: "እንደ ሹፌር ይቀጥሉ",
    phoneAuth: "በስልክ ቁጥር ይግቡ",
    enterPhone: "የስልክ ቁጥርዎን ያስገቡ",
    sendOtp: "ኮድ ይላኩ",
    verifyOtp: "ኮዱን ያረጋግጡ",
    riderHome: "የት መሄድ ይፈልጋሉ?",
    requestRide: "ጉዞ ይዘዙ",
    fareEstimate: "የዋጋ ግምት",
    driverDashboard: "የሹፌር መቆጣጠሪያ",
    goOnline: "ስራ ይጀምሩ",
    goOffline: "ስራ ያቁሙ",
    earnings: "ገቢ",
    history: "ታሪክ",
    adminDashboard: "የአስተዳዳሪ መቆጣጠሪያ",
    stats: "ስታቲስቲክስ",
    users: "ተጠቃሚዎች",
    rides: "ጉዞዎች",
    resendOtp: "ኮድ ድጋሚ ላክ",
    personal: "የግል",
    business: "የስራ",
    rewards: "ሽልማቶች",
    points: "ነጥቦች",
    safetyPin: "የደህንነት ኮድ",
    verifyPin: "ኮዱን አረጋግጥ",
    startTrip: "ጉዞ ጀምር",
    completeTrip: "ጉዞ ጨርስ",
    arrive: "ደርሻለሁ",
  },
  om: {
    welcome: "Baga Gara Zeyago Ride nagaan dhuftan",
    continueRider: "Akka imalaatti itti fufi",
    continueDriver: "Akka konkolaachisaatti itti fufi",
    phoneAuth: "Mirkaneessa bilbilaa",
    enterPhone: "Lakkoofsa bilbilaa keessan galchaa",
    sendOtp: "Koodii ergi",
    verifyOtp: "Koodii mirkaneessi",
    riderHome: "Eessa deemuu barbaadda?",
    requestRide: "Imala ajajadhu",
    fareEstimate: "Tilmaama gatii",
    driverDashboard: "Daashboordii konkolaachisaa",
    goOnline: "Hojii jalqabi",
    goOffline: "Hojii dhaabi",
    earnings: "Galii",
    history: "Seenaa",
    adminDashboard: "Daashboordii bulchiinsaa",
    stats: "Istaatistiksii",
    users: "Fayyadamtoota",
    rides: "Imalawwan",
    resendOtp: "Koodii deebisii ergi",
    personal: "Dhuunfaa",
    business: "Hojii",
    rewards: "Badhaasawwan",
    points: "Qabxiiwwan",
    safetyPin: "PIN Nageenyaa",
    verifyPin: "PIN Mirkaneessi",
    startTrip: "Imala Jalqabi",
    completeTrip: "Imala Xumuri",
    arrive: "Gahameera",
  }
};
